[package]
name = "test_lib"
version = "0.1.0"
authors = ["teo <teokaltrachian16@hotmail.com>"]
edition = "2018"

[dependencies]
matrice_lib = { path = "../matrice_lib" }
city_position_lib = { path = "../city_position_lib" }
genetic_algorithms = { path = "../genetic_algorithms" }
