[package]
name = "genetic_algorithms"
version = "0.1.0"
authors = ["teo <teokaltrachian16@hotmail.com>"]

[dependencies]
matrice_lib = { path = "../matrice_lib" }
city_position_lib = { path = "../city_position_lib" }
plotlib = { path = "../plotlib" }
rand = "0.3"
